// Builds src/app/map/data.ts and assets/terminal-map.jpg from docs/reference/terminal-map.html
// (Colby's download of the Terminal & Yard Map artifact) plus the artifact's saved edits
// (docs/reference/terminal-map-edits.json). Geometry only; all logic lives in src/app/map/model.ts.
// Re-run after re-downloading the HTML or re-exporting the edits:  node scripts/export-map.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const html = readFileSync('docs/reference/terminal-map.html', 'utf8');
const base = html.match(/EDIT_BASE='([^']+)'/)?.[1];
const line = html.split('\n').find((l) => l.startsWith('var D={'));
const b64 = html.match(/<image id="sat" href="data:image\/jpeg;base64,([A-Za-z0-9+/=]+)"/)?.[1];
if (!base || !line || !b64) throw new Error('terminal-map.html: base, geometry or satellite image not found; the artifact layout changed.');
const D = JSON.parse(line.slice('var D='.length).replace(/;\s*$/, '')); // \s: Windows checkouts end lines with CRLF

// Saved edits (the artifact's database doc map/edits). Refused if they were made on another base version.
const file = JSON.parse(readFileSync('docs/reference/terminal-map-edits.json', 'utf8'));
const e = JSON.parse(file.edits);
if (e.base !== base || file.base !== base) throw new Error(`Edits are for base ${e.base}, the HTML is ${base}. Re-export the edits.`);
const unsupported = Object.keys(e).filter((k) => !['base', 'items', 'rail'].includes(k));
if (unsupported.length) throw new Error(`Edits contain ${unsupported.join(', ')}, which this script does not apply yet.`);
const applied = [];
for (const [id, v] of Object.entries(e.items ?? {})) {
  const it = D.items.find((x) => x.id === id);
  if (!it || !v?.poly || v.poly.length < 3) throw new Error(`Edit for ${id} does not match a map lot.`);
  it.poly = v.poly; if (v.lab) it.lab = v.lab; applied.push(id);
}
for (const [n, pts] of Object.entries(e.rail ?? {})) if (D.rail[n] && pts?.length >= 2) { D.rail[n] = pts; applied.push(`rail:${n}`); }

const items = D.items.map(({ id, name, label, short, type, poly, lab, cut, src, note }) => ({ id, name, label, short, type, poly, lab, cut, src, note }));
const land = D.land.map(({ id, label, kind, x, y, dx, dy }) => ({ id, label, kind, x, y, dx, dy }));
const out = { w: D.W, h: D.H, ftPerUnit: D.S, baseVersion: base, editsApplied: applied, items, land, rail: D.rail, roads: D.roads, nroads: D.nroads };

mkdirSync('assets', { recursive: true });
writeFileSync('assets/terminal-map.jpg', Buffer.from(b64, 'base64'));
writeFileSync('src/app/map/data.ts', `// GENERATED by scripts/export-map.mjs from docs/reference/terminal-map.html + terminal-map-edits.json. Do not edit.
// Coordinates are map units (the satellite image's pixels); ftPerUnit converts them to feet (an estimate, protocol 7.4).
export type Pt = [number, number];
export type MapItem = { id: string; name: string; label: string; short: string; type: 'zone' | 'site' | 'yard' | 'oem'; poly: Pt[]; lab: Pt; cut: 15 | 30 | null; src: 'sheet' | 'loc'; note: string };
export type Landmark = { id: string; label: string; kind: 'berth' | 'place' | 'road' | 'rail'; x: number; y: number; dx: number; dy: number };
export const MAP: { w: number; h: number; ftPerUnit: number; baseVersion: string; editsApplied: string[]; items: MapItem[]; land: Landmark[]; rail: { ramp: Pt[]; yard: Pt[] }; roads: Pt[][]; nroads: { id: string; name: string; w: number; pts: Pt[] }[] } = ${JSON.stringify(out)};
`);
console.log(`items ${items.length}, landmarks ${land.length}, edits applied: ${applied.join(', ') || 'none'}, image ${(b64.length * 0.75 / 1024).toFixed(0)} KB`);
